updated workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -220,6 +220,7 @@ jobs:
       CHANGE_SET: ${{ steps.changeset.outputs.CHANGE_SET }}
       STACK_NAME: ${{ steps.changeset.outputs.STACK_NAME }}
       DATE: ${{ steps.s3.outputs.DATE }}
+      S3_STATUS: ${{ steps.s3.outcome }}
     
   wait_for_stack:
       runs-on: codebuild-AwsLabsMultiAZWorkshopArm64GithubRunner-${{ github.run_id }}-${{ github.run_attempt }}
@@ -232,10 +233,10 @@ jobs:
           run: |
             echo "Waiting for CloudFormation stack to complete..."
             get_change_set_status() {
-              aws cloudformation describe-change-set \
+              aws cloudformation describe-stacks \
               --stack-name "$STACK_NAME" \
               --change-set-name "$CHANGE_SET" \
-              --query "ChangeSet.Status" \
+              --query "Stacks[0].StackStatus" \
               --region $AWS_REGION \
               --output text
             }
@@ -246,28 +247,76 @@ jobs:
             # Loop to monitor the status of the change set
             while true; do
                 case "$STATUS" in
+                    "CREATE_COMPLETE")
+                      echo "Creation is complete"
+                      exit 0
+                      ;;
                     "CREATE_IN_PROGRESS")
-                        echo "Change set is being created, waiting..."
-                        ;;
+                      echo "Change set is being created, waiting..."
+                      ;;
                     "CREATE_FAILED")
-                        echo "Change set creation failed!"
-                        exit 1
-                        ;;
-                    "EXECUTE_IN_PROGRESS")
-                        echo "Change set is being executed, waiting..."
-                        ;;
-                    "EXECUTE_FAILED")
-                        echo "Change set execution failed!"
-                        exit 1
-                        ;;
-                    "EXECUTE_COMPLETE")
-                        echo "Change set executed successfully!"
-                        exit 0
-                        ;;
+                      echo "Change set creation failed!"
+                      exit 1
+                      ;;
+
+                    "DELETE_COMPLETE")
+                      echo "Delete complete"
+                      exit 1
+                      ;;
+                    "DELETE_FAILED")
+                      echo "Delete failed"
+                      exit 1
+                      ;;
+                    "DELETE_IN_PROGRESS")
+                      echo "Delete in progress, waiting..."
+                      ;;
+
+                    "REVIEW_IN_PROGRESS")
+                      echo "Review in progress, waiting"
+                      ;;
+
+                    "ROLLBACK_COMPLETE")
+                      echo "Create failed and rolled back"
+                      exit 1
+                      ;;
+                    "ROLLBACK_FAILED")
+                      echo "Create failed and rollback failed"
+                      exit 1
+                      ;;
+                    "ROLLBACK_IN_PROGRES")
+                      echo "Rollback in progress, waiting"
+                      ;;
+
+                    "UPDATE_COMPLETE")
+                      echo "Update complete"
+                      exit 0
+                      ;;
+                    "UPDATE_COMPLETE_CLEANUP_IN_PROGRESS")
+                      echo "Update finishing, waiting..."
+                      ;;
+                    "UPDATE_IN_PROGRESS")
+                      echo "Update in progress, waiting"
+                      ;;
+
+                    "UPDATE_ROLLBACK_COMPLETE")
+                      echo "Update failed"
+                      exit 1
+                      ;;
+                    "UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRES")
+                      echo "Update rollback cleanup, waiting..."
+                      ;;
+                    "UPDATE_ROLLBACK_FAILED")
+                      echo "Update failed, rollback failed"
+                      exit 1
+                      ;;
+                    "UPDATE_ROLLBACK_IN_PROGRESS")
+                      echo "Update rollback in progress, waiting"
+                      ;;
+                   
                     *)
-                        echo "Unknown status: $STATUS"
-                        exit 1
-                        ;;
+                      echo "Unknown status: $STATUS"
+                      exit 1
+                      ;;
                 esac
 
                 # Wait for 30 seconds before checking the status again
@@ -280,6 +329,8 @@ jobs:
   cleanup:
     runs-on: codebuild-AwsLabsMultiAZWorkshopArm64GithubRunner-${{ github.run_id }}-${{ github.run_attempt }}
     needs: [ wait_for_stack, test ]
+    if: |
+      ${{ needs.test.outputs.S3_STATUS }} == 'success' && (needs.wait_for_stack.result == 'success' || needs.wait_for_stack.result == 'failure' || needs.wait_for_stack.result == 'skipped')
     env:
       DATE: ${{ needs.test.outputs.DATE }}
       BUCKET: workshop-pipeline-wspipelineartifactsbucket5608ec1-xqbqfqtepjdl
@@ -294,5 +345,5 @@ jobs:
         if: needs.wait_for_stack.result != 'success'
         run: |
           echo Deleting new S3 content because deployment did not succeed
-          aws s3 rm s3://$BUCKET/ --recursive --include "$DATE/*"
+          aws s3 rm s3://$BUCKET/ --recursive --exclude "*" --include "$DATE/*"
           
