new image pull logic

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -139,13 +139,29 @@ jobs:
 
       - name: Pull istio containers
         run: |
+            MAX_RETRIES=10
+            SLEEP_INTERVAL=2
             ACCOUNT_ID=$(echo "$CODEBUILD_BUILD_ARN" | cut -d':' -f5)
             aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
             IMAGES=(install-cni proxyv2 pilot operator)
             BASE=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/docker-hub
             for image in "${IMAGES[@]}"; do
-              docker pull $BASE/istio/$image:$ISTIO
-              docker tag $BASE/istio/install-cni:$ISTIO istio/install-cni:$ISTIO
+              SOURCE=$BASE/istio/$image:$ISTIO
+              docker pull $SOURCE
+              
+              retries=0
+              while ! docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "^$SOURCE$"; do
+                if [ "$retries" -ge "$MAX_RETRIES" ]; then
+                  echo "Image $SOURCE did not appear in 'docker images' after $((MAX_RETRIES * SLEEP_INTERVAL)) seconds. Exiting."
+                  exit 1
+                fi
+
+                echo "Retry $((retries+1))/$MAX_RETRIES - Image not found yet. Retrying in $SLEEP_INTERVAL seconds..."
+                sleep "$SLEEP_INTERVAL"
+                retries=$((retries+1))
+              done
+
+              docker tag $SOURCE istio/$image:$ISTIO
               docker save istio/$image:$ISTIO | gzip > ${{ github.workspace }}/assets/$image.tar.gz
             done
             
