updating wait logic and cleanup

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -69,6 +69,11 @@ jobs:
           cd ${{ github.workspace }}/$CDK_LOCATION/layer
           zip -r ${{ github.workspace }}/$CDK_LOCATION/helm-layer.zip .
 
+      - name: Copy destination rule
+        run: 
+          file=destination-rule.yaml
+          cp ${{ github.workspace }}/$CDK_LOCATION/Configs/$file ${{ github.workspace }}/assets/$file
+
       - name: Get kubectl
         run: |
           file=kubectl
@@ -79,13 +84,13 @@ jobs:
           BASE=https://istio-release.storage.googleapis.com/charts
           istio_deps=("base-$ISTIO.tgz" "istiod-$ISTIO.tgz" "gateway-$ISTIO.tgz" "cni-$ISTIO.tgz")
           for file in ${istio_deps[@]}; do
-            curl --location $BASE/$file --output ${{ github.workspace }}/assets/${file%%-*}.tgz
+            curl --location $BASE/$file --output ${{ github.workspace }}/assets/$file
           done
 
       - name: Get AWS load balancer controller
         run: |
           file=aws-load-balancer-controller-$LB_CONTROLLER_HELM.tgz
-          curl --location https://aws.github.io/eks-charts/$file --output ${{ github.workspace }}/assets/${file%%-*}.tgz
+          curl --location https://aws.github.io/eks-charts/$file --output ${{ github.workspace }}/assets/$file
 
       - name: Pull istio container images
         run: |
@@ -180,6 +185,7 @@ jobs:
         with:
           name: ContentArtifact
           path: ${{ github.workspace }}/content.zip
+
   test:
     needs: [ build ]
     runs-on: codebuild-AwsLabsMultiAZWorkshopArm64GithubRunner-${{ github.run_id }}-${{ github.run_attempt }}
@@ -193,32 +199,100 @@ jobs:
           name: ContentArtifact
 
       - name: Upload to S3
-        run: |
-          mkdir -p ${{ github.workspace }}/content
-          unzip content.zip -d ${{ github.workspace }}/content
-          aws s3 cp ${{ github.workspace }}/content s3://$BUCKET/ --recursive
-
-      - name: Deploy change set
+        id: s3
         run: |
           date=$(date --utc +"%Y-%m-%dT%H-%M-%SZ")
-          aws cloudformation create-change-set --stack-name $PROJECT_NAME --change-set-name $PROJECT_NAME-$date --template-url https://$BUCKET.s3.amazonaws.com/$PROJECT_NAME.template --parameters ParameterKey=AssetsBucketName,ParameterValue=$BUCKET ParameterKey=AssetsBucketPrefix,ParameterValue="" ParameterKey=ParticipantRoleName,ParameterValue=Admin --capabilities CAPABILITY_IAM --region $AWS_REGION
+          echo "DATE=$date" >> $GITHUB_OUTPUT
+          mkdir -p ${{ github.workspace }}/content
+          unzip content.zip -d ${{ github.workspace }}/content
+          aws s3 cp ${{ github.workspace }}/content s3://$BUCKET/$date/ --recursive
+
+      - name: Deploy change set
+        id: changeset
+        run: |
+          date=${{ steps.s3.outputs.DATE }}
+          aws cloudformation create-change-set --stack-name $PROJECT_NAME --change-set-name $PROJECT_NAME-$date --template-url https://$BUCKET.s3.amazonaws.com/$PROJECT_NAME.template --parameters ParameterKey=AssetsBucketName,ParameterValue=$BUCKET ParameterKey=AssetsBucketPrefix,ParameterValue=$date ParameterKey=ParticipantRoleName,ParameterValue=Admin --capabilities CAPABILITY_IAM --region $AWS_REGION
           aws cloudformation wait change-set-create-complete --stack-name $PROJECT_NAME --change-set-name $PROJECT_NAME-$date --region $AWS_REGION
           aws cloudformation execute-change-set --stack-name $PROJECT_NAME --change-set-name $PROJECT_NAME-$date --region $AWS_REGION
+          echo "CHANGE_SET=$PROJECT_NAME-$date" >> "$GITHUB_OUTPUT"
+          echo "STACK_NAME=$PROJECT_NAME" >> "$GITHUB_OUTPUT"
+    outputs:
+      CHANGE_SET: ${{ steps.changeset.outputs.CHANGE_SET }}
+      STACK_NAME: ${{ steps.changeset.outputs.STACK_NAME }}
+      DATE: ${{ steps.s3.outputs.DATE }}
     
   wait_for_stack:
       runs-on: codebuild-AwsLabsMultiAZWorkshopArm64GithubRunner-${{ github.run_id }}-${{ github.run_attempt }}
       needs: [ test ]
       env:
-        PROJECT_NAME: ${{ github.event.repository.name }}
+        CHANGE_SET: ${{ needs.test.outputs.CHANGE_SET }}
+        STACK_NAME: ${{ needs.test.outputs.STACK_NAME }}
       steps:
         - name: Wait for CloudFormation Stack to complete
           run: |
             echo "Waiting for CloudFormation stack to complete..."
-            aws cloudformation wait stack-create-complete --stack-name $PROJECT_NAME --region $AWS_REGION
-            if [ $? -ne 0 ]; then
-              echo "CloudFormation stack deployment failed."
-              exit 1
-            else
-              echo "CloudFormation stack deployed successfully."
-            fi
+            get_change_set_status() {
+              aws cloudformation describe-change-set \
+              --stack-name "$STACK_NAME" \
+              --change-set-name "$CHANGE_SET" \
+              --query "ChangeSet.Status" \
+              --region $AWS_REGION \
+              --output text
+            }
+
+            # Initial status check
+            STATUS=$(get_change_set_status)
+            
+            # Loop to monitor the status of the change set
+            while true; do
+                case "$STATUS" in
+                    "CREATE_IN_PROGRESS")
+                        echo "Change set is being created, waiting..."
+                        ;;
+                    "CREATE_FAILED")
+                        echo "Change set creation failed!"
+                        exit 1
+                        ;;
+                    "EXECUTE_IN_PROGRESS")
+                        echo "Change set is being executed, waiting..."
+                        ;;
+                    "EXECUTE_FAILED")
+                        echo "Change set execution failed!"
+                        exit 1
+                        ;;
+                    "EXECUTE_COMPLETE")
+                        echo "Change set executed successfully!"
+                        exit 0
+                        ;;
+                    *)
+                        echo "Unknown status: $STATUS"
+                        exit 1
+                        ;;
+                esac
+
+                # Wait for 30 seconds before checking the status again
+                sleep 30
+
+                # Get the current status again
+                STATUS=$(get_change_set_status)
+            done
+          
+  cleanup:
+    runs-on: codebuild-AwsLabsMultiAZWorkshopArm64GithubRunner-${{ github.run_id }}-${{ github.run_attempt }}
+    needs: [ wait_for_stack, test ]
+    env:
+      DATE: ${{ needs.test.outputs.DATE }}
+      BUCKET: workshop-pipeline-wspipelineartifactsbucket5608ec1-xqbqfqtepjdl
+      PROJECT_NAME: ${{ github.event.repository.name }}
+    steps: 
+      - name: Cleanup Old S3 Content
+        if: needs.wait_for_stack.result == 'success'
+        run: |
+          echo Deleting old S3 content due to deployment success
+          aws s3 rm s3://$BUCKET/ --recursive --exclude "$DATE/*"
+      - name: Cleanup New S3 Content
+        if: needs.wait_for_stack.result != 'success'
+        run: |
+          echo Deleting new S3 content because deployment did not succeed
+          aws s3 rm s3://$BUCKET/ --recursive --include "$DATE/*"
           
